language: php

# 使用的php版本
php:
- 7.1
- 7.2
- 7.3

dist: trusty
sudo: false

# 构建前执行的命令
# travis_retry 重试3次执行后面的命令
# --no-interaction：不要询问任何交互问题   --prefer-source：从版本库下载
install:
- travis_retry composer install --no-interaction --prefer-source

# 项目构建脚本
script: vendor/bin/phpunit --verbose